services:
  - type: web
    runtime: python
    name: AI_Research_Assistant
    rootDir: backend
    buildCommand: pip install -r requirements_deploy.txt
    startCommand: alembic upgrade head && uvicorn main:app --host 0.0.0.0 --port $PORT

  - type: web
    runtime: static
    name: ai-research-assistant-frontend
    rootDir: frontend
    buildCommand: npm install && npm run build
    staticPublishPath: dist
    routes:
      - type: rewrite
        source: /*
        destination: /index.html