"""phase_21_1_research_projects

Revision ID: a7d6acf68893
Revises: a085fd97da1e
Create Date: 2026-07-15 21:18:40.627482

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a7d6acf68893'
down_revision: Union[str, Sequence[str], None] = 'a085fd97da1e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('projects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_projects_id'), 'projects', ['id'], unique=False)
    op.add_column('chat_sessions', sa.Column('project_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'chat_sessions', 'projects', ['project_id'], ['id'], ondelete='SET NULL')
    op.add_column('documents', sa.Column('project_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'documents', 'projects', ['project_id'], ['id'])
    op.add_column('research_notes', sa.Column('project_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'research_notes', 'projects', ['project_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'research_notes', type_='foreignkey')
    op.drop_column('research_notes', 'project_id')
    op.drop_constraint(None, 'documents', type_='foreignkey')
    op.alter_column('documents', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('documents', 'project_id')
    op.drop_constraint(None, 'chat_sessions', type_='foreignkey')
    op.drop_column('chat_sessions', 'project_id')
    op.drop_index(op.f('ix_projects_id'), table_name='projects')
    op.drop_table('projects')
    # ### end Alembic commands ###
